# NVIDIA GTX 1660 SUPER - GTX 1660 SUPER
# DP-2:   AOC 27G2G4 @ 144Hz (monitor principal)
# HDMI-0: segundo monitor @ 60Hz
# ForceCompositionPipeline: elimina tearing
# TripleBuffer: reduz input lag

Section "Device"
    Identifier  "Device0"
    Driver      "nvidia"
    Option      "TripleBuffer" "true"
EndSection

Section "Screen"
    Identifier  "Screen0"
    Device      "Device0"
    Option      "metamodes" "DP-2: 1920x1080_144 +0+0 {ForceCompositionPipeline=On, ForceFullCompositionPipeline=On}, HDMI-0: 1920x1080_60 +1920+0 {ForceCompositionPipeline=On, ForceFullCompositionPipeline=On}"
    Option      "TripleBuffer" "true"
EndSection
