Section "InputClass"
    Identifier  "Logitech G502 X"
    MatchProduct "Logitech G502 X"
    MatchIsPointer "yes"
    Driver "libinput"
    Option "AccelProfile" "flat"
    Option "AccelSpeed" "-0.15"
EndSection
