# If you come from bash you might have to change your $PATH.
# export PATH=$HOME/bin:/usr/local/bin:$PATH
export PATH=$HOME/bin:/usr/local/bin:$PATH:$HOME/.cargo/bin:$HOME/.local/bin:$
export ZSH="$HOME/.oh-my-zsh"
export BROWSER="brave"
export EDITOR=nvim
export VISUAL=nvim
export SUDO_EDITOR=nvim

ZSH_THEME="intheloop"

plugins=(
    git
    archlinux
    zsh-autosuggestions
    zsh-syntax-highlighting
)

source $ZSH/oh-my-zsh.sh

# Check archlinux plugin commands here
# https://github.com/ohmyzsh/ohmyzsh/tree/master/plugins/archlinux

# Display Pokemon-colorscripts
# Project page: https://gitlab.com/phoneybadger/pokemon-colorscripts#on-other-distros-and-macos
#pokemon-colorscripts --no-title -s -r #without fastfetch
#pokemon-colorscripts --no-title -s -r | fastfetch -c $HOME/.config/fastfetch/config-pokemon.jsonc --logo-type file-raw --logo-height 10 --logo-width 5 --logo -

# fastfetch. Will be disabled if above colorscript was chosen to install
fastfetch -c $HOME/.config/fastfetch/config-compact.jsonc

# Set-up icons for files/directories in terminal using lsd
alias ls='lsd'
alias l='ls -l'
alias la='ls -a'
alias lla='ls -la'
alias lt='ls --tree'

alias vim='nvim'

# Scripts
alias firewall_sshd='sudo ~/.config/i3/Scripts/sshd_firewall_on_off.sh'
alias listagem_pacotes='~/.config/i3/Scripts/listagem_pacote.sh'

# Bluetooth 
alias bluetoothon='sudo systemctl start bluetooth && blueman-manager'
alias bluetoothoff='sudo systemctl stop bluetooth'

# Files
alias i3config='code ~/.config/i3/config'
alias zshrc='code ~/.zshrc'
alias i3blocks='code ~/.config/i3/i3blocks.conf'

# Set-up FZF key bindings (CTRL R for fuzzy history finder)
source <(fzf --zsh)

HISTFILE=~/.zsh_history
HISTSIZE=10000
SAVEHIST=10000
setopt appendhistory
